### ISSUE TITLE
toolbar dropdown

### ISSUE THREAD

**Issue by cokipg** [LeonStaufer/material-dokuwiki#22]
Hi,
the dropdown of the editor-toolbar is not working. E.g. if I click on the button for headers or smileys or WRAP-Plugin there is no dropdown.
If I switch to the standard dokuwiki template it is working, so it's not a plugin causing this error.
I also reinstalled the material template, to overwrite my changes... it's still not working.

I found a passage in .../css/fixes.less
`.mdl-layout__content {
  background: @background_white;
  display: flex;
  flex-direction: column;
}
`
If I remove those lines, obviously some things don't look right anymore. But strangely now the dropdown of toolbar buttons works. However the dropdown is in the background behind the wiki page and only sticking out to the right, and clicking on the buttons in the dropdown has no effect.

Do you have any idea what the problem could be? I am an html beginner, so it's hard for me to understand the template code.

I am using 2018-04-22a "Greebo".

**Comment by LeonStaufer** [comment]
Thank you for your detailed issue report. 

I'm looking into what could be causing this and as soon as I (or anyone else) finds a solution I will push an update.

**Comment by LeonStaufer** [comment]
Okay, the problem was that the dropdown menus were below the content, as you already mentioned.
A quick fix was adding a `z-index` value above that of the content so it can be seen.

I've also styled the buttons slightly so they are more inline with the material design.

For now, you can add the following code to the `fixes.less` file and I will properly incorporate the changes next release.

``` css
.picker {
    z-index: 99999;
    .pickerbutton {
        background: white;
        border: none;
        margin: 0px;
        ._shadow_1dp;
    }
    .toolbutton {
        background: white;
        border: none;
        margin: 0px;
        ._shadow_1dp;
    }
}
```
