### ISSUE TITLE
Strange design in the mobile view

### ISSUE THREAD

**Issue by herbertvonkaramalz** [LeonStaufer/material-dokuwiki#23]
The side menu protrudes about 3 millimeters from the side and looks funny ... how can this be fixed?

**Comment by LeonStaufer** [comment]
Yea, I do see how it can look funny. It was a purposeful design decision, however, I understand that not everyone may like it, so to change it remove the ``width: 18.5em`` from  ``.mdl-layout__drawer`` in the ``fixes.less``.

``` css
.mdl-layout__drawer {
  overflow: overlay;
  ._shadow_3dp;
  background: rgb(24,31,105);
  background: @primary_dark;
  border: none;
  width: 18.5em;
  color: @light_secondary;
}
```
