### ISSUE TITLE
Hiding redundant h1 in div.content-card__text

### ISSUE THREAD

**Issue by GJRobert** [LeonStaufer/material-dokuwiki#3]
Hi Leon,

I see you have designed a `div.content-card__title` which looks nice. Also as you mentioned in Line 129~135 that
``` php
                <div class="content-card__text">
                    <?php
                    if ($conf['useheading'] == 1){
                        //TODO: find out what to with the title
                    }
                    tpl_content(); ?>
                </div>
```
, while the title maybe trimmed with future implementations, right now I'm using a line in my userall.css to hide that h1 in `div.content-card__text`:
``` css
div#dokuwiki__top.tpl_material:not(.notFound) div.content-card__title + div.content-card__text h1:first-of-type {display: none;}
```
- I think that on pages with 404 status, the heading should be kept since `div.content-card__title` only contains the page ID;
- On special tools like Media Manager or Recent Changes, there is not `div.content-card__title`, therefore the h1 in `div.content-card__text` should is the only h1 on page and should not be hidden in this case.

Above is just for your reference before you further development the way avoid redundant page heading :) Thanks again for this beautiful design.

Cheers,
Robert
