### ISSUE TITLE
Change indentation of links

### ISSUE THREAD

**Issue by LeonStaufer** [LeonStaufer/material-dokuwiki#30]
Issue added thanks to feedback from Tin. 

Currently, the indentation of the links in the navigation bar are hardcoded and this width might not fit for all use cases. It would be good if it could be edited in the configuration settings.

Until then you can change it by adding the following in `basic.less` to `.mdl-navigation`:
```css
.mdl-navigation {
  margin-top: 16px;
  /* ... */
  .level1{
    ul {
      padding-left: 15px;
    }
  }
}
```

You can replace `15px` with any width of your liking. 

This only applies if you are using the "use DokuWiki sidebar option".
