### ISSUE TITLE
Cannot change page/sidebar width

### ISSUE THREAD

**Issue by SwayYe** [LeonStaufer/material-dokuwiki#40]
I tried to modify the value of `__site_width__` and `__sidebar_width__`. 
However, neither modification through DokuWiki administration panel nor local style.ini works.
Is this a bug? Or can I change the layout by editing the .less directly? Sorry about the bothering, I am new to website design.

**Comment by LeonStaufer** [comment]
Thanks, @SwayYe. As far as I know, `__site_width__` is a configuration property that is not standard to all templates. It is provided by default DokuWiki template though, as you can see [here](https://www.dokuwiki.org/template:dokuwiki#customizing).

In any case, it would be a helpful configuration option to add, so I have labelled this as an enhancement. 

In the meantime, you can edit the `css/fixes.less` file at [line 92](https://github.com/LeonStaufer/material-dokuwiki/blob/master/css/fixes.less#L92) and add the following to edit `.mdl-layout__drawer` like so:
```css
.mdl-layout__drawer {
  overflow: overlay;
  ._shadow_3dp;
  background: rgb(24,31,105);
  background: @primary_dark;
  border: none;
  color: @light_secondary;

  width: YOUR_WIDTH;
  left: -YOUR_WIDTH;
}
```
Notice the `left` property is the negative of your preferred width.

**Comment by SwayYe** [comment]
Thanks for your help!
I tried to add these two lines in `css/fixes.less` and set `YOUR_WIDTH=40em`, but it seems that the site width is not changed.

**Comment by LeonStaufer** [comment]
Try flushing the cache and force reloading the page. Let me know if it still does not work

**Comment by SwayYe** [comment]
I tried to recache the website, still not working.
BTW, I find out that the sidebar becomes folded by default, which is the only difference after I edited `css/fixes.less`.
![45ada8a423dab8368d38d3d22b73f2b](https://user-images.githubusercontent.com/31896670/84591611-74f5ec00-ae72-11ea-9d67-53f09cdab9cc.png)
![47c43e5cec631d62a5ad42dc2f7aaae](https://user-images.githubusercontent.com/31896670/84591650-cc945780-ae72-11ea-934a-4a9e5bc84f5b.png)

![43fb7e95a559e8d016f8e903b0b93aa](https://user-images.githubusercontent.com/31896670/84591615-79220980-ae72-11ea-9d53-0e581108f8b8.png)

**Comment by LeonStaufer** [comment]
My bad, this is a little more complicated because the drawer has two states, depending on the size of the screen. I've tested the following updated solution and it works locally. `400px` is a just a size I experimented, with but you can replace it with any width you like.

```css
.mdl-layout__drawer {
  overflow: overlay;
  ._shadow_3dp;
  background: rgb(24,31,105);
  background: @primary_dark;
  border: none;
  color: @light_secondary;
  left: -400px;
  width: 400px;
}

:not(.is-small-screen).mdl-layout {
  .mdl-layout__drawer {
    width: 400px;
    left: 0;
  }
  .mdl-layout__drawer.is-visible {
    left: 0;
  }

  .mdl-layout__header{
    margin-left: 400px !important;
    width: calc(100% - 240px) !important;
  }

  .mdl-layout__content {
    margin-left: 400px;
  }
}
```

Unfortunately, `width: calc(100% - 240px) !important;` breaks the header, but I can't seem to figure out why :/
